title:       Feedbin Blog
description: Rediscover RSS
domain:      http://blog.feedbin.com
email:       support@feedbin.com
permalink:   pretty
pygments:    true
paginate:    10
exclude:     [public, vendor, .bundle, log, Gemfile, Gemfile.lock, Capfile, config, lib]
asset_url:
  - hosted: //me-feedbin-blog.global.ssl.fastly.net/assets
  - local: /assets